# Generated by Django 6.0 on 2025-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_trc', '0002_expense_delete_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
